version: 0.0
os: linux
files:
  - source: hello-world/
    destination: /home/ec2-user/slack-app
hooks:
  BeforeInstall:
    - location: scripts/test.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_deployment.sh
      timeout: 300
      runas: root
