name: test-notification

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build app
      run: ./gradlew build

    - name: Deploy app to AWS
      uses: actions/aws/code_deploy@v1
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY }}
        secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: my-application-name
        deployment_group: my-deployment-group
        region: ap-south-1
        file: build/libs/hello-world-0.1-all.jar
